# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: deaa96c8b63c6b83f8e73f12b6cb7ce6c40e2d1fad131b422b9aa958904cdb6a500bf96a3133266c62e2e2770768f8b7a7f620f7294b55ad7ee0f1d656fec277

test:
  secret_key_base: 94a639e700eb6fa6322460533f68c552a3bbc70eb5a87efaf9c913aa6fa8e7b26c99ae67d8547791341f487d973df0fc4c263f5c1152e03d880371703281216e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
